fix(justfile): 'exec' recipe improved

diff --git a/src/justfile b/src/justfile
--- a/src/justfile
+++ b/src/justfile
@@ -1,5 +1,9 @@
 set dotenv-load
 
+command_std := '/bin/bash'
+command_app := command_std
+command_db  := 'psql -U postgres'
+
 alias rs := restart
 
 _default:
@@ -85,39 +89,61 @@ ps all='':
 		echo "Docker deamon is stopped."
 	fi
 
-# run a shell inside a container
-exec: up
+# run a command inside a container
+[positional-arguments]
+exec *args='': up
 	#!/bin/bash
+
 	if ! command -v jq &>/dev/null; then
 	    echo "Error: jq not found"
 		exit 0
 	fi
-	
-	containers=$(docker compose ps --format json | jq -rs 'map(.Name) | @sh // empty' | tr -d \')
-	if [ -n "$containers" ]; then
-		if ! command -v fzf &>/dev/null; then
-			select container_name in $containers;
-			do
-				if [ $REPLY -ge 1 ] && [ $REPLY -le $(echo $containers | wc -w) ]; then
-					break
-				fi
-			done
-		else
-			container_name=$(echo -n "$containers" \
-				| tr ' ' '\n' \
-				| fzf --exact --reverse --border --header-first --header "ESC. quit")
-		fi
-		
-		if [ -z "${container_name}" ]; then
-			echo "Error: no container selected"
-			exit 1
-		fi
 
-		echo "Getting into ${container_name}..."
-		docker exec -it "${container_name}" /bin/bash
-	else
-		echo "No container available"
+	containers=$(docker compose ps --format json \
+		| jq -rs 'map(.Name) | @sh // empty' \
+		| tr -d \')
+	
+	if [ -z "$containers" ]; then
+		echo "Error: no container available"
+		exit 1
 	fi
+
+	if [ -z "${EXEC_RECIPE_CHOOSER}" ]; then
+		select container_name in $containers;
+		do
+			if [ $REPLY -ge 1 ] && [ $REPLY -le $(echo $containers | wc -w) ]; then
+				break
+			fi
+		done
+	else
+		container_name=$(echo -n "$containers" \
+			| tr ' ' '\n' \
+			| bash -c "${EXEC_RECIPE_CHOOSER}")
+	fi
+	
+	if [ -z "${container_name}" ]; then
+		echo "Error: no container selected"
+		exit 1
+	fi
+
+	if [ -n "$1" ]; then 
+		command="$@"
+	else
+		case "${container_name#*_}" in
+			app)
+				command="{{command_app}}"
+				;;
+			db)
+				command="{{command_db}}"
+				;;
+			*)
+				command="{{command_std}}"
+				;;
+		esac
+	fi
+
+	echo "Getting into ${container_name}..."
+	docker exec -it "${container_name}" $command
 
 # build images
 build: on
